### ISSUE TITLE
Malformed URL

### ISSUE THREAD

**Issue by amgarr** [hippothomas/waistline-api#4]
I am getting an error when attempting to instantiate the database and reset the cache. Error is "Malformed URL". 

Not sure what the issue with my URL is. I defined it in env.local.

**Comment by hippothomas** [comment]
Hi! Could you give me more information about your environment and how did you setup the app?

If you are using docker compose, it may be an issue from the database url, the defaults one needs to be changed.
At least the host needs to change from the default value "127.0.0.1", like this :

```
DATABASE_URL="postgresql://app:!ChangeMe!@waistline-api_postgres:5432/waistline?serverVersion=16&charset=utf8"
MONGODB_URL="mongodb://root:!ChangeMe!@waistline-api_mongodb:27017"
```

It could also come from your database password, if you have a special character in it, you may need to encode it.

**Comment by amgarr** [comment]
Thanks, I had the host set up wrong.

Now I am getting an error with connecting to postgresql server. Logs are below. I dont have any special characters in the postgres or mongodb passwords. should I change from scram-sha-256?

I am setting it up using Docker compose. 

2024-02-28 16:06:07 2024-02-28 21:06:07.306 UTC [34] FATAL:  password authentication failed for user "app"
2024-02-28 16:06:07 2024-02-28 21:06:07.306 UTC [34] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"

**Comment by hippothomas** [comment]
It may be because you changed the password after initializing the database, in this case you could delete the `data` folder and rerun `docker compose up -d`. It will recreate everything based on your new configuration.

**Comment by amgarr** [comment]
I have rerun docker compose and still getting the same issue.

**Comment by hippothomas** [comment]
This seems to be a configuration issue and I will need more details to be able to help you, can you show me your `docker-compose.yml` ?

**Comment by amgarr** [comment]
I have gotten it running but I don't think I have the `APP_BASE_URL` set up correctly. I got postgres runningby adjusting `pg_hba.conf` My `docker-compose.yml` is below. I can't access the API using the service address. 

```
version: '3.8'
services:
  waistline-api:
    image: waistline-api:latest
    container_name: waistline-api
    depends_on:
      - postgres
      - mongodb
    volumes:
      - .env.local:/var/www/html/.env.local
      - ./data/log:/var/log/apache2/ #optional
    ports:
      - "8081:80"
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/api/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped

  postgres:
    image: postgres:16.1
    container_name: waistline-api_postgres
    environment:
      POSTGRES_DB: 'waistline'
      POSTGRES_USER: 'app'
      POSTGRES_PASSWORD: '<password>'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: waistline-api_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: '<password>'
    volumes:
      - ./data/mongodb:/data/db
    restart: unless-stopped
```
